---
stages:
  - test
  - build
  - deploy

before_script:
  - chmod +x ./gradlew
  - ./gradlew clean


test job:
  stage: test
  tags:
    - runner
  script:
    - ./gradlew test

build job:
  stage: build
  tags:
    - runner
  script:
    - ./gradlew bootjar

deploy job:
  stage: deploy
  tags:
    - runner
  script:
    - sudo docker-compose up --build

